name: CI
on: pull_request
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v13
      - run: sbt scalafmtCheckAll
      - run: sbt coreJVM/test
      - run: sbt coreJS/test
      - run: sbt webserver/test
